# Generated by Django 3.2.4 on 2021-06-23 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=100)),
                ('Age', models.CharField(blank=True, max_length=100)),
                ('Address', models.CharField(blank=True, max_length=500)),
                ('Email', models.CharField(blank=True, max_length=100)),
                ('Mob_no', models.CharField(blank=True, max_length=100)),
                ('City', models.CharField(blank=True, max_length=100)),
                ('Current_Designation', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
